### ISSUE TITLE
Any compatibility with Quark?

### ISSUE THREAD

**Issue by nikiforr** [ThatGravyBoat/Ironchests#1]
Hello! I've noticed the chests from this mod don't support quark features, such as searching or sorting items. Are there may be any plans to add it in future?

**Comment by zachsai** [comment]
You can add it with quark itself, they allow it in their config

**Comment by MrJorman** [comment]
can I find out exactly where this configuration is?

**Comment by MrJorman** [comment]
**quark-common.toml** there are no such configurations.

**Comment by ThatGravyBoat** [comment]
It is in `quark-common.toml` the option is `Allowed Screens` and you need to put `tech.thatgravyboat.ironchests.client.ChestScreen` in the list in quotes.
