### ISSUE TITLE
Idea For Update: Changing Netherite Chest

### ISSUE THREAD

**Issue by MikeTheBuddy** [ThatGravyBoat/Ironchests#11]
I've noticed the netherite chest burns in lava, despite the fact that pretty much everything netherite doesn't.

I was thinking maybe give the chest the property to not burn and lava and just float back to the top like other netherite items.

**Comment by ThatGravyBoat** [comment]
oh forgot about that ill look into changing this

**Comment by ThatGravyBoat** [comment]
Ive added this it will be added when the next time I update.
