### ISSUE TITLE
Chest Brightness

### ISSUE THREAD

**Issue by Oscillate18** [ThatGravyBoat/Ironchests#12]
The chests from the mod look unnatural when placed due to the high brightness they have compared to the vanilla blocks. This is especially noticeable with the iron, gold and diamond chests. Could this be altered as it is such a fantastic mod of very high quality just like your others. 

![2022-06-17_20 33 13](https://user-images.githubusercontent.com/65877846/174390501-e0288175-4d1d-4709-a37f-99579fc0c0bc.png)

**Comment by MrJorman** [comment]
+ and Quark mod no support. GG WP.

**Comment by ThatGravyBoat** [comment]
> * and Quark mod no support. GG WP.

That is very much irrelevant to this bug report, you can go ask the quark developers to add support for this.

**Comment by ThatGravyBoat** [comment]
But the actually bug in this bug report will be fixed next update it was fixed in 1.19 it just needs to be backported

**Comment by ThatGravyBoat** [comment]
Update for 1.18 has been pushed to fix the glowing chests.

**Comment by leagris** [comment]
@ThatGravyBoat the fix in ironchests-2.0.3-forge does not work. See screenshot where chests are still overly bright:
![2022-06-18_17 10 34](https://user-images.githubusercontent.com/1111474/174444774-c66354af-ecfb-464e-8bf6-f99ca58f0501.png)

**Comment by Oscillate18** [comment]
Also experiencing the exact same issue as above with the latest version. You can see the lighting issue when compared to the diamond block, it is so much brighter and unnatural.
![2022-06-18_19 23 22](https://user-images.githubusercontent.com/65877846/174451690-193306cf-bc63-4dc7-b9de-8e99b37f7335.png)

**Comment by ThatGravyBoat** [comment]
I need to look into this much more because from my testing it's very random with how bright it is and it doesn't really make much sense I thought I fixed it in 1.19 but it was just that when I tested it it was in a chunk where it didn't make it super bright and kind of normal.

**Comment by Oscillate18** [comment]
> I need to look into this much more because from my testing it's very random with how bright it is and it doesn't really make much sense I thought I fixed it in 1.19 but it was just that when I tested it it was in a chunk where it didn't make it super bright and kind of normal.

No worries, appreciate you looking into this. It's only a visual bug so not super important.

**Comment by sirben99** [comment]
Hey

Just wanted to report that this is happening for me too. This still being looked into? 
Below is a screenshot. Running 2.0.3-Fabric, 1.18.2.
(The screenshot seems to make it abit darker, its more brighter ingame)
![2022-07-17_21 28 59](https://user-images.githubusercontent.com/32977052/179419818-abf282c7-126f-45be-8647-d183c617f821.png)

**Comment by MrJorman** [comment]
too problem

**Comment by ThatGravyBoat** [comment]
Fixed in 1.18 fix will come to 1.19 soon
