### ISSUE TITLE
QUARK NO CRAFTING YOUR CHEST! AND NO UPGRADE!

### ISSUE THREAD

**Issue by MrJorman** [ThatGravyBoat/Ironchests#13]
I have Quark installed with a bunch of different wooden chests, I can't use them in crafting to get your improved chests, as well as chest improvements don't work on them, FIX it! I can't use your cool mod on the server because of this.

**Comment by MrJorman** [comment]
![image](https://user-images.githubusercontent.com/55187962/174445451-324b0eb5-e3b7-4b3c-b5b7-e6f4bd577e44.png)
no working upgrade and craft

**Comment by MrJorman** [comment]
![image](https://user-images.githubusercontent.com/55187962/174445485-fb230ac1-14e1-40e4-8dc6-a6b66550f5f6.png)
and your chest glowing lol

**Comment by Oscillate18** [comment]
> I have Quark installed with a bunch of different wooden chests, I can't use them in crafting to get your improved chests, as well as chest improvements don't work on them, FIX it! I can't use your cool mod on the server because of this.

Manners cost nothing my man, saw you in the issue I posted being the exact same.

You even got a response from the dev about this issue in the issue I created, "That is very much irrelevant to this bug report, you can go ask the quark developers to add support for this."

**Comment by Oscillate18** [comment]
Also you can literally turn them back into normal chests via this recipe, the chests will then work fine with the upgrades and to craft the chests.
![2022-06-18_19 37 59](https://user-images.githubusercontent.com/65877846/174452050-c2830f4f-bc52-42cb-bdf0-73cbe70f9f62.png)

**Comment by ThatGravyBoat** [comment]
There is a tag provided that you can add quark chests into that allows them to be upgraded, all you need to do is add the chest block id to the `ironchests:upgradeable_wooden_chests` tag, I will not put them in the tag by default because there is more than just quark that adds new chests and I do not want to start the precedent that I will keep adding mods to this tag when either the mod can add it themself or if the mod doesn't the user/pack dev can easily with 1 file.

Also, be nice to mod devs we make these mods for free so being rude does not do anything but annoy us and question if we should even make mods if all people do is complain and be rude. 🙂

**Comment by MrJorman** [comment]
> There is a tag provided that you can add quark chests into that allows them to be upgraded, all you need to do is add the chest block id to the `ironchests:upgradeable_wooden_chests` tag, I will not put them in the tag by default because there is more than just quark that adds new chests and I do not want to start the precedent that I will keep adding mods to this tag when either the mod can add it themself or if the mod doesn't the user/pack dev can easily with 1 file.
> 
> Also, be nice to mod devs we make these mods for free so being rude does not do anything but annoy us and question if we should even make mods if all people do is complain and be rude. 🙂

And where to add this tag?

**Comment by MrJorman** [comment]
and Craft tag? yes?

**Comment by MrJorman** [comment]
```{
  "replace": false,
  "values": [
    "minecraft:chest",
	"quark:oak_chest",
	"quark:spruce_chest",
	"quark:birch_chest",
	"quark:jungle_chest",
	"quark:acacia_chest",
	"quark:dark_oak_chest",
	"quark:crimson_chest",
	"quark:warped_chest",
	"quark:nether_brick_chest",
	"quark:purpur_chest",
	"quark:prismarine_chest",
	"quark:azalea_chest",
	"quark:blossom_chest"
  ]
}``` no working upgrade

**Comment by MrJorman** [comment]
![image](https://user-images.githubusercontent.com/55187962/174466540-15437a11-6877-4be9-a3f1-4cf7243df0bd.png)

**Comment by MrJorman** [comment]
ok. fixed. nice.
