### ISSUE TITLE
Iron Chests Restocked failed to load correctly with Forge 41.0.87

### ISSUE THREAD

**Issue by Gamemassa** [ThatGravyBoat/Ironchests#14]
MC Version: 1.19
Forge version 41.0.87
Mod version: 3.0.2

Hi,

I tried to load Minecraft with the latest versions of Forge and Iron Chests Restocked and encountered the following error message:
![image](https://user-images.githubusercontent.com/18667108/178146393-eac29bdb-9344-4bef-8ebb-eda9872861b8.png)

[crash-2022-07-10_09.11.50-fml.txt](https://github.com/ThatGravyBoat/Ironchests/files/9079125/crash-2022-07-10_09.11.50-fml.txt)

**Comment by ThatGravyBoat** [comment]
For now the mod is broken on versions after 41.0.64 I will fix it in the coming day or 2

**Comment by Gamemassa** [comment]
Awesome! Thanks for the quick response.
