### ISSUE TITLE
Adjacent chests not connecting

### ISSUE THREAD

**Issue by Gamemassa** [ThatGravyBoat/Ironchests#15]
Hi, I'm just curious, are the chests from Iron Chests: Restocked supposed to merge together when you put two of them side-by-side, like with vanilla chests? I've noticed that they aren't merging for me and I'm not sure if they are intended to or not. If not, no big deal, I just didn't see anything about it on the CurseForge page so I thought I'd ask.

**Comment by ThatGravyBoat** [comment]
It is intended that they do not connect.

**Comment by Gamemassa** [comment]
Gotcha. Thank you for confirming.
