### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by zymmas** [ThatGravyBoat/Ironchests#17]
Hey there, I notice your mod doesn't really have sufficient documentation.  The only real documentation I can find is the infographic on the mod page itself, and that hardly says anything.  You go into more detail about the two auxiliary parts of the mod, that is to say the ability to lock and the ability to move, than you do the actual main attraction: the chests themselves.

You don't really provide any information at all for the various chests, which makes using them a guessing game, at best.  You don't provide it on your mod page or via a book in game or even as a tooltip when hovering over the item in an inventory or similar, any of which would be sufficient and immensely helpful.

As one easy example of the lack of documentation being an issue, I have absolutely zero idea what the difference between the obsidian chest, the diamond chest, and the crystal chest is other than aesthetics.

Another example, it'd be quite helpful to know the storage space of a chest before committing resources to making it.  Is it better than a normal chest?  Does it have the same space but just looks different?  It's impossible to know without first making it.

So I hope you see my issue.  I know there was an original Iron Chests mod, it kind of seems like you're relying on the player having prior knowledge of that mod and its chests to know the difference between the chests themselves.  If that is the case then, and perhaps it's just me, that feels like a bit too much faith to have in one's users.

I hate having to guess at things so if you could include some documentation somewhere obvious about each of the chest variants it'd be highly appreciated.  Thank you very much for your time.

**Comment by ThatGravyBoat** [comment]
the documentation would be very useless its pretty simple the better the material the bigger the chest and it has the attributes of that material. There is developer documentation for if you want to add your own custom chests using the json API but that is about it.

**Comment by Slaymeister** [comment]
I'm having the same issue.  The curseforge page graphic says the chests have "different properties and sizes". "Sizes" is self explanatory though details would be nice. More confusing, though, is that the diamond chest upgrades to both obsidian and netherite. (In the pack I'm playing there is also a diamond to crystal upgrade.  I'm not sure that's in the base mod.) Clearly those two are better than diamond, therefore, but are they the same? Is there a property difference between the two? Can one be picked up without a hand cart? Is one of them nestable? Can one be retextured? Does one follow you like a lonely puppy until you give it a ball to play with? Or is it just more size than diamond but different than each other? Even in-mod tooltips would be a big help, which would leave any pack-added details up to whomever added them.

**Comment by ThatGravyBoat** [comment]
The crystal allows items to be shown without opening the chest because it's see-through and the obsidian is explosion-proof.

**Comment by zymmas** [comment]
I've found by making them that the obsidian also appears to be the same size as diamond, so it's not so much an upgrade as it is an enhancement to the base diamond chest.  The crystal is also an enhancement and is the same size as diamond.  The only one of the three paths that actually upgrades the chest is the netherite one as that one increases storage space.

To this extent to elaborate on Slay thinking they're better than diamond, I'd say "better" is a bit subjective in this context.  Better in that they have an additional property?  Sure.  Better as in they perform their function of storage better?  No.

**Comment by Slaymeister** [comment]
Is the netherite chest also blast proof, or is that property exclusive to the obsidian chest? The crystal chest may be see through, but it doesn't render items. That's good for lag.  It's easily broken compared to other chests on it's tier, which is good for temporary/development builds.

**Comment by zymmas** [comment]
That's a good question and I have no answer as it doesn't say anywhere on the mod page or the like, yet given the developer didn't mention that as a feature for the netherite it seems unlikely, but they may have just decided not to mention as crystal and obsidian were the topics.  Hard to say.  Unfortunately, as well, I can't test it as my partner and I have stopped playing for the moment.  It's a pity there isn't some basic info readily available by someone who would actually know about, at least, the three 'final tier' chests.

**Comment by Coryf88** [comment]
| Type | Size | Blast Resistance
| - | - | -
| Dirt | 1x1 (1) | Dirt
| Copper | 9x4 (36) | Stone
| Iron | 9x6 (54) | Stone
| Gold | 11x6 (66) | Stone
| Diamond | 12x6 (72) | Stone
| Crystal | 12x6 (72) | Glass
| Obsidian | 12x6 (72) | Obsidian
| Netherite | 13x7 (91) | Obsidian
