### ISSUE TITLE
How do you change chest sizes?

### ISSUE THREAD

**Issue by tbmny** [ThatGravyBoat/Ironchests#19]
I tried to increase the inventory size of the diamond chests to 12x12, so I edited the json to 12 length and 12 rows, but it's unchanged in game, so I'm assuming this isn't the way to do it.

**Comment by ThatGravyBoat** [comment]
the ui is not dynamic so if you change it to 12x12 there will be 12x12 slots but the texture for the chest wont change you would need to create one to match the new dimensions that you created.
