### ISSUE TITLE
Suggestion: upgrade chests from other wood types

### ISSUE THREAD

**Issue by tinytransfem** [ThatGravyBoat/Ironchests#20]
So I use Quark and it adds chests for each wood variant, and in combination with other mods even more chest types are added, which function just like the normal chest but have a different texture. I really like using these as it gives my storage room a nice variety.

Now with Iron Chests installed, I don't get to use these other chests if I want maximum storage space. Would you be willing to add some kind of compatibility for this? Possibly make all chests upgradeable without changing their texture, or make it possible to apply textures of other chests onto Iron Chests chests .

**Comment by ThatGravyBoat** [comment]
fixed in [7ddd4af](https://github.com/ThatGravyBoat/Ironchests/commit/7ddd4af6e590a4f289562364ff477ac1e07dbfef) but this can also be done via a datapack using the tag while I wait until to release the next update.
