### ISSUE TITLE
Add Compatibility with Woodworks and Compat O' Plenty

### ISSUE THREAD

**Issue by LolJohn11** [ThatGravyBoat/Ironchests#21]
Please add compatibility for the following chests to be converted to Ironchests and their variants.
I've tried doing it through a datapack alone but it didn't work, seems like you need to add [Blueprint](https://www.curseforge.com/minecraft/mc-mods/blueprint) as a mod dependency to make this work.

[Woodworks](https://www.curseforge.com/minecraft/mc-mods/woodworks):
```
woodworks:oak_chest
woodworks:birch_chest
woodworks:spruce_chest
woodworks:jungle_chest
woodworks:acacia_chest
woodworks:dark_oak_chest
woodworks:mangrove_chest
woodworks:crimson_chest
woodworks:warped_chest
```
[Compat O' Plenty](https://www.curseforge.com/minecraft/mc-mods/compat-o-plenty):
```
compatoplenty:cherry_chest
compatoplenty:jacaranda_chest
compatoplenty:fir_chest
compatoplenty:redwood_chest
compatoplenty:mahogany_chest
compatoplenty:willow_chest
compatoplenty:magic_chest
compatoplenty:dead_chest
compatoplenty:umbran_chest
compatoplenty:palm_chest
compatoplenty:hellbark_chest
```
The latter one has a lot more potential chest blocks, so it would be great to add all of them as compatibility as well.

**Comment by ThatGravyBoat** [comment]
You shouldnt need to have a dependency for this to work can you send how you made the datapack because it should work.

**Comment by LolJohn11** [comment]
@ThatGravyBoat You were correct, I made a mistake while creating the datapack. Fixed it and it works.
