### ISSUE TITLE
[crash upon startup] 

### ISSUE THREAD

**Issue by DanMeadWasTaken** [ThatGravyBoat/Ironchests#25]
minecraft 1.19.2 quilt

https://mclo.gs/9YoL39t

**Comment by ThatGravyBoat** [comment]
I do not support quilt natively, so can you get this reproduced on fabric?

**Comment by DanMeadWasTaken** [comment]
It'd seem quilt was the issue after all- which is odd, almost all the fabric mods I've used also work for quilt even if not stated to do as such natively.
