### ISSUE TITLE
Comparator no working

### ISSUE THREAD

**Issue by MrJorman** [ThatGravyBoat/Ironchests#28]
Comparator no working 
![image](https://user-images.githubusercontent.com/55187962/226150640-40322b61-4815-49ba-ba85-a0a523c349b0.png)
![image](https://user-images.githubusercontent.com/55187962/226150643-6a468558-0bd7-4cb2-a8fa-cd48669cd3ec.png)

**Comment by MrJorman** [comment]
fix pls ?

**Comment by ThatGravyBoat** [comment]
It's literally been 3 days, people have lives they aren't going to reply or respond right away, wait and be patient.

**Comment by MrJorman** [comment]
Fixed?
