### ISSUE TITLE
Locked chest doesn't work

### ISSUE THREAD

**Issue by SenpaiV0ID** [ThatGravyBoat/Ironchests#29]
I am trying to attach a gold lock to a gold chest but it wont let me attach it.

**Comment by ThatGravyBoat** [comment]
Shift right click with the lock to attach it

**Comment by SenpaiV0ID** [comment]
> Shift right click with the lock to attach it

I do that and it still wont work I am using it from All of fabric 5 in curse forge will this effect the mod?

**Comment by ThatGravyBoat** [comment]
I just tested and it worked fine so it may be another mod in the pack
