### ISSUE TITLE
Padlock dupe

### ISSUE THREAD

**Issue by FoxSketchez** [ThatGravyBoat/Ironchests#3]
Atm 7 Version 0.3.21 / 1.18.2
Iron chests:r 1.3.0

Using a diamond dolly to pickup any iron chest mod chest with a open or closed padlock results in giving a padlock to user, as well as leaving a padlock on moved chest that is still able to be used as the original lock

**Comment by ThatGravyBoat** [comment]
Fixed in version 2.0.0
