### ISSUE TITLE
Inventory Sorter Quark support 

### ISSUE THREAD

**Issue by WanderBoi** [ThatGravyBoat/Ironchests#32]
Could we have these functions supported? 
![image](https://user-images.githubusercontent.com/29160030/227668730-fb85daf2-5960-464d-bfb3-6e216023a83e.png)

**Comment by ThatGravyBoat** [comment]
Those can be added in the quark config, last I checked I cant add them they have to be done by quark or by the user via the config.

**Comment by guivnf** [comment]
> Those can be added in the quark config, last I checked I cant add them they have to be done by quark or by the user via the config.

This issue still persists yk, and the main problem with this is that you apparently don't extend the normal chest class. 
https://github.com/VazkiiMods/Quark/issues/4617

Not only this but there isn't a proper config option for users to add chest like blocks. I'd appreciatte if this issue would get re-opened and taken care of, but really i don't think both quark or users can do anything about it, as this is on your side.

**Comment by ThatGravyBoat** [comment]
Quark can easily fix their sorting, you do not need to extend vanilla menus for slot sorting to work, you also can't extend vanilla menus like that for menus like mine due to vanilla restriction on the slot count being a multiple of 9. There is nothing I can do, this is all on quark, other sorting mods sort menus like mine completely fine with zero issue out of the box.

**Comment by ThatGravyBoat** [comment]
If you want a sorting mod that works, I suggest simple inventory sorter

**Comment by MetalKnight56** [comment]
> If you want a sorting mod that works, I suggest simple inventory sorter

Yeah i've tried that as well and neither work...

**Comment by guivnf** [comment]
> If you want a sorting mod that works, I suggest simple inventory sorter

Got it, thanks for the reply on this :)

**Comment by Kurizek27** [comment]
> Those can be added in the quark config, last I checked I cant add them they have to be done by quark or by the user via the config.
no they cannot. 

![Image](https://github.com/user-attachments/assets/20c180b8-1ca7-4fec-9b03-129098a06d89)

![Image](https://github.com/user-attachments/assets/3628780b-b59b-4ecc-9e56-f99f70afbf53)
