### ISSUE TITLE
Config doesn't work properly

### ISSUE THREAD

**Issue by Auuki** [ThatGravyBoat/Ironchests#34]
I've tried changing chest sizes using json files in config and I couldn't get the numbers to work well. I thought that maybe I mess up height or something but then I copied over the iron into copper and it did increase the container size but didn't adjust the UI. Trying the same using datapack resulted in the same outcome.

**Comment by ThatGravyBoat** [comment]
the UI is an image it isnt automatic as of right now they are a separate texture that needs to be changed or added, possibly in the future I will make it automatically generated but not right now
