### ISSUE TITLE
Multiplayer Chest Dupe

### ISSUE THREAD

**Issue by Namefix** [ThatGravyBoat/Ironchests#39]
This dupe works with two players. When player 1 opens the chest, player 2 breaks it simultaneously, resulting in the duplication of the chest. It's important to note that only the chest itself is duplicated, not its contents.

Video demonstration:
https://youtu.be/u1E6zdSrMpk

**Comment by GitJhopa** [comment]
please fix in 1.19.2 forge.. and silent chest in spectator.
