### ISSUE TITLE
Chest Upgrades don´t work on barrels, making upgraded barrels uncraftable

### ISSUE THREAD

**Issue by Diego13303** [ThatGravyBoat/Ironchests#48]
What the title says. Trying to shift click a barrel with a Copper Chest Upgrade does nothing. As far as I can tell, that means there´s no way of getting the several Barrel upgrades already implemented in the mod in Survival mode

**Comment by Diego13303** [comment]
This was closed without any comment..?
Is it a planned feature? A bug or mistake on my end?

**Comment by ThatGravyBoat** [comment]
Chest upgrades arnt meant to work on barrels, there are now crafting recipes

**Comment by Diego13303** [comment]
Ah I just now noticed the mod was updated. Thank you!

**Comment by PinkLasagna03** [comment]
> Chest upgrades arnt meant to work on barrels, there are now crafting recipes

Can you make some "barrel upgrades"? It's a pain in the ass to upgrade them while they are full with items
