### ISSUE TITLE
All Chests Gone?

### ISSUE THREAD

**Issue by sweetsosweet** [ThatGravyBoat/Ironchests#5]
Not sure how the new system is supposed to work, does it not start with any defaults? Are we meant to start creating the chests from scratch as jsons?

I upgraded form [ironchest-1.18-1.0.1.jar](https://www.curseforge.com/minecraft/mc-mods/ironchests/files/3541861)

to 

[[Fabric] Iron Chests 2.0.1](https://www.curseforge.com/minecraft/mc-mods/ironchests/files/3789925)

And there are no defaults (config folders are empty and default.lock is 0 bytes) and now all my items + chests are gone. :(

I'm using fabric-api-0.51.1+1.18.2 and I've also tested on a fresh instance with only fabric api and the iron chests mod. Only item in game is the blank chest upgrade.

![2022-05-14_20 19 32](https://user-images.githubusercontent.com/15041593/168452281-9e407a87-9ec6-4069-96f6-49796259669a.png)

Forgot to include my log:
[latest.log](https://github.com/ThatGravyBoat/Ironchests/files/8694084/latest.log)

**Comment by ThatGravyBoat** [comment]
I guess fabric does some weird stuff with the file system thing outside of dev ill have to check.

**Comment by ThatGravyBoat** [comment]
For now ive just archived the fabric version on curseforge just so others don't run into this issue but when I figure out why fabric produces completely different results for dev and production ill make the fix and push it out.

**Comment by ThatGravyBoat** [comment]
This should be fixed in 2.0.2 if it does not make a new issue. Note: you will have to delete the defaults.lock file for it to generate them with this fix.
