### ISSUE TITLE
Dolly can be put in a shulker using a hopper

### ISSUE THREAD

**Issue by Philanche** [ThatGravyBoat/Ironchests#50]
Playing on Fabric, in 1.19.2.
As said in title, dollies can be put in a shulker box by putting a hopper pointing inside the shulker box and then throwing a dolly into the hopper. This is a pretty important problem, because it allows carrying a dolly without the normal penalty, and some mods (such as supplementaries) use this feature to check whether or not an item can go into other inventories that can be carried.

**Comment by Philanche** [comment]
It has been over 2 months, is there any update on this?

**Comment by ThatGravyBoat** [comment]
This is a vanilla issue https://bugs.mojang.com/browse/MC-253951
