### ISSUE TITLE
please 1.19.2 forge new updates.

### ISSUE THREAD

**Issue by GitJhopa** [ThatGravyBoat/Ironchests#51]
please 1.19.2 forge new updates.

**Comment by Epic428** [comment]
Wtf kind of questions even is this?

**Comment by GitJhopa** [comment]
I wrote about bugs with chests that the comporator does not work and do not open silently in the spectator mode. Fixes were made for 1.20, but they forgot about 1.19.2, although I asked for 1.19.2

**Comment by Epic428** [comment]
Perhaps then being more explicit with the title and the body text would be helpful.

**Comment by GitJhopa** [comment]
sorry

**Comment by Fade-Alchemist** [comment]
Including recipes for Barrels were also forgotten for 1.19.2  (which **was** explicitly stated in the title and the body of the text.)

**Comment by Epic428** [comment]
> (which **was** explicitly stated in the title and the body of the text.)

it’s fine if a different github issue specifically mentioned what was missing or needed to be done. My point is that the title of this github issue and the body text is literally:

“please 1.19.2 forge new updates” 

like wtf does that even mean? How does any person looking or searching through github issues have any idea what this specific issue is in regard to with such vague and ambiguous text?

the issue should read something along the lines of: 

“Backport 1.20 features and updates to 1.19.2 please.”

As that is far more concise. The body text can even provide examples of what needs to be backported or is missing.
