### ISSUE TITLE
Suggestion: Project name conflict

### ISSUE THREAD

**Issue by kingstairs** [ThatGravyBoat/Ironchests#6]
There is at least one other Iron Chests project around: [Iron Chests for Fabric](https://www.curseforge.com/minecraft/mc-mods/iron-chests-for-fabric) - I believe there is also a separate Forge version.

This would not be an issue except that the download filenames seem to be the same (_IronChests-x.y.z_), which can make it difficult to identify which Iron Chests mod I'm actually installing (or updating).

Perhaps rename the download to something like "_TGB-IronChests-x.y.z_" to uniquely identify it?
Thank you.

**Comment by ThatGravyBoat** [comment]
There is not really a point to doing this as you can't use both together anyway as they both use the same modid so even if you downloaded both you wouldn't be able to start the game and I won't be changing the modid as it will break existing worlds.
