### ISSUE TITLE
Glitched GUI texture on Crystal and Obsidian Chest

### ISSUE THREAD

**Issue by ShiroFenixlm** [ThatGravyBoat/Ironchests#64]
Hi, when opening one of those chest the inventory interface is all glitched

![image](https://github.com/ThatGravyBoat/Ironchests/assets/30911462/997c4193-86c5-45a7-a61c-1dc42170e65f)

I found this error on the log, In case it helps:
![image](https://github.com/ThatGravyBoat/Ironchests/assets/30911462/7f892038-ca52-4ccf-9bcf-3dbdf889c82e)

**Comment by ThatGravyBoat** [comment]
A config was probs copied from an old version of the mod where I had individual textures for each chest
