### ISSUE TITLE
 Missing Textures

### ISSUE THREAD

**Issue by Infinituum17** [ThatGravyBoat/Ironchests#65]
#### Version: 5.0.2 - ResourcefulLib Version: 2.1.16

I'm developing my own mod that interacts with this one and I've noticed some textures are missing.

### Crystal Chest:
![image](https://github.com/ThatGravyBoat/Ironchests/assets/40234342/339f3d84-19f4-4884-823e-900779e01ea7)

### Obsidian Chest:
![image](https://github.com/ThatGravyBoat/Ironchests/assets/40234342/685a3d07-897c-4eff-aefe-3324961a6a64)

### Console:
```
[01:08:41] [Render thread/WARN] (Minecraft) Failed to load texture: ironchests:textures/gui/chests/diamond.png
 java.io.FileNotFoundException: ironchests:textures/gui/chests/diamond.png
```

**Comment by ThatGravyBoat** [comment]
make sure your config folder does not contain files from previous mc versions

**Comment by Infinituum17** [comment]
ok this fixed everything, tysm

**Comment by ThatGravyBoat** [comment]
Ill pin this for others that may run into it
