### ISSUE TITLE
Crash Upon Chest Upgrade

### ISSUE THREAD

**Issue by digi-draws** [ThatGravyBoat/Ironchests#66]
I am not heavy into crash reports and stuff so I can put that here too if needed, I'm not sure if I'm just missing something though.

https://github.com/ThatGravyBoat/Ironchests/assets/151573487/020b46a8-4fa9-47e9-a84d-ebe928cd98a2

**Comment by ThatGravyBoat** [comment]
I need a crash log

**Comment by digi-draws** [comment]
[crash-2023-11-20_14.42.03-client.txt](https://github.com/ThatGravyBoat/Ironchests/files/13432029/crash-2023-11-20_14.42.03-client.txt)

**Comment by digi-draws** [comment]
I know it has something to do with another mod I have but I don't know what is conflicting between the two.

**Comment by ThatGravyBoat** [comment]
it does seem to be an incompatibility with 'Hey That's Mine' which incorrectly assumes that lockable containers cant only be used server side and crashes because of that

**Comment by ThatGravyBoat** [comment]
this needs to be given to them
