### ISSUE TITLE
Crystal Chest Doesn't Show Inventory With Closed Lid

### ISSUE THREAD

**Issue by JayeConcord** [ThatGravyBoat/Ironchests#67]
The Crystal Chests/Barrels are meant to show what's in their inventory, which I thought was a nifty little feature. The Crystal Barrel works as intended, but the Crystal Chest will only display what's inside of it whilst the lid is open, as when the lid is closed, it looks like it's empty.

**Comment by ThatGravyBoat** [comment]
This is due to transparency ordering in Minecraft due to this it will only do this if you have fabulous graphics mode where transparency ordering is changed to work correctly, you will also see this issue in vanilla with items that have transparency in water.

**Comment by JayeConcord** [comment]
Weird that you need to downgrade your graphics to make things look better. Thank you for letting me know.

**Comment by ThatGravyBoat** [comment]
Fabulous graphics is a higher graphics option
