### ISSUE TITLE
Large chests

### ISSUE THREAD

**Issue by marlester-dev** [ThatGravyBoat/Ironchests#68]
What do you think about large (double) chests support? I didn't find a similar issue.
![Large Chest GIF](https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e1/Large_Chest.gif)

**Comment by Pendrag00n** [comment]
I was expecting this to be already implemented when I installed the mod...

**Comment by marlester-dev** [comment]
> I was expecting this to be already implemented when I installed the mod...

Yeah, me too

**Comment by ThatGravyBoat** [comment]
No large chests are not planned, the UI space is already limited, doubling the size will not make it better
