### ISSUE TITLE
Loot tables are not supported

### ISSUE THREAD

**Issue by SuperHeroBaga** [ThatGravyBoat/Ironchests#70]
Placing one of the mod's entity blocks by /setblock command or modifyng the data with the tag {LootTable:" *any loot table path* "} won't work and the container will always be empty. Also the same behavior is observed when placing one of the containers by hand with nbt value of {BlockEntityTag:{LootTable:" *any loot table path* "}}.

The mod is really cool and would be awesome if it supported loot table generation!

**Comment by ThatGravyBoat** [comment]
I just extend the class, if it does not work then idk what to do
