### ISSUE TITLE
How to disable "container" name in chests via resourcepack? (1.19.2)

### ISSUE THREAD

**Issue by Tuna7822** [ThatGravyBoat/Ironchests#75]
I am trynig this

  "container.chest.dirt_chest": "",
  "container.chest.copper_chest": "",
  "container.chest.iron_chest": "",
  "container.chest.gold_chest": "",
  "container.chest.diamond_chest": "",
  "container.chest.crystal_chest": "",
  "container.chest.obsidian_chest": "",
  "container.chest.netherite_chest": "",
  
  But this not working. Whats wrong?
  
  
![image](https://github.com/ThatGravyBoat/Ironchests/assets/158822209/0be556f7-7d5e-46f9-816a-e273cb91d404)
![image](https://github.com/ThatGravyBoat/Ironchests/assets/158822209/53aada26-e5d4-44cd-9c15-050eff207685)

**Comment by ThatGravyBoat** [comment]
it uses the block name not the container
