### ISSUE TITLE
How to make custom GUI texture for crystal and obsidian chests? (1.19.2)

### ISSUE THREAD

**Issue by Tuna7822** [ThatGravyBoat/Ironchests#76]
I am already done with all chests GUI retexture but crystal and obsidian chests still uses diamond texture in UI. How can I fix that?

![image](https://github.com/ThatGravyBoat/Ironchests/assets/158822209/c3a84939-9d40-4fa2-b97d-bfd3dd8122ae)
![image](https://github.com/ThatGravyBoat/Ironchests/assets/158822209/f7bb3f22-a34e-41e5-a511-c10ca1de2391)
![image](https://github.com/ThatGravyBoat/Ironchests/assets/158822209/405d2b45-98b5-45d6-812f-9b18a3b9e68c)
![image](https://github.com/ThatGravyBoat/Ironchests/assets/158822209/036ae395-6b94-4815-ac4c-bebb412aad99)
![image](https://github.com/ThatGravyBoat/Ironchests/assets/158822209/7502ffc0-9d8c-4830-8abd-b0889c242683)

**Comment by ThatGravyBoat** [comment]
Remove the line `"texture": "diamond",` from the obsidian and crystal chest json in your config folder
