### ISSUE TITLE
crystal chest becomes transparent with the use of Complementary Shaders v4

### ISSUE THREAD

**Issue by OlegFive** [ThatGravyBoat/Ironchests#8]
google translate - the crystal chest becomes transparent with the use of Complementary Shaders v4
![2022-06-07_03 29 06](https://user-images.githubusercontent.com/107009701/172270942-e0dfce79-05d8-4421-bbd9-cdfaad1eb436.png)

**Comment by ThatGravyBoat** [comment]
This seems like a bug with the shaders and not the mod because all I do is set the chest to have a transparent renderer like a lot of other blocks in the game.
